### ISSUE TITLE
Support regexp

### ISSUE THREAD

**Issue by inigomarquinez** [guidesmiths/license-checker#20]
Example case:

The project is using a `AGPL-3.0` license.

If we run `--failOn AGPL`, the command doesn't fail.

We can enhance the library to support a kind of RegExp for `--failOn` and `--generateOutputOn `parameters, for example `--failOn AGPL*`  would fail for the given example.

**Comment by s1mrankaur** [comment]
any update here?

npx @guidesmiths/license-checker --summary --failOn 'apache'

does not fail

but

npx @guidesmiths/license-checker --summary --failOn 'Apache-2.0' does so doesn't seem to be working as mentioned in https://github.com/guidesmiths/license-checker/pull/31
