### ISSUE TITLE
Case insensitive comparison

### ISSUE THREAD

**Issue by inigomarquinez** [guidesmiths/license-checker#21]
We should compare licenses without taking into account upper or lower case

**Comment by shikhar13012001** [comment]
I would love to work on this could you assign it to me ?

**Comment by jmtorralvo** [comment]
@shikhar13012001 Feel free to take any issue.  👍 

The only thing to do is update each ticket on the board and put it into Progress column
https://github.com/guidesmiths/license-checker/projects/1
